### ISSUE TITLE
El comportamiento de la nueva UI de test es aleatorio y con errores

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-bibliotheca-ui#195]
Si el ejercicio ya tiene las vestimentas, el tablero a veces aparece con las vestimentas puestas y no se puede modificar. Además, al cambiar ciertos valores se achica mucho o aparece descentrado con el título pisando al tablero. 

Dejo los videos para reproducir todas las pruebas: 
https://youtu.be/_A1tvzlmXp8
https://youtu.be/P9c_aPbuTDI

@fedescarpa

**Comment by flbulgarelli** [comment]
Otro problema que tiene es que se rompe cuando el YAML tiene elementos que la UI no soporta, como por ejemplo con `endless_while`....

```yaml
expect_endless_while: true
check_head_position: false
examples:
 - initial_board: |
     GBB/1.0
     size 2 2
     cell 0 1 Negro 4 Rojo 4 
     cell 1 1 Azul 6 Rojo 4 
     cell 0 0 Negro 4 Rojo 4 
     cell 1 0 Negro 4 Rojo 4 
     head 1 1
```

se ve así:


![image](https://user-images.githubusercontent.com/677436/46365688-a05d8680-c64f-11e8-8d9c-27e36de7ab85.png)

**Comment by flbulgarelli** [comment]
Ver video de @rodri042 Video: https://www.youtube.com/watch?v=nfViKk57ccM
