### ISSUE TITLE
No se puede crear una guía si no se seleccionan explícitamente ciertas opciones

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-bibliotheca-ui#210]
Al crear una guía, si no se seleccionan explícitamente las opciones de visibilidad y tipo de guía, se tiene el siguiente error: 

![image](https://user-images.githubusercontent.com/677436/47307393-4c6a1000-d605-11e8-871c-cbd087ca84b7.png)

Si se eligen estas opciones con lo mismos valores por defecto, funciona.

**Comment by rodri042** [comment]
Como puse en https://github.com/mumuki/mumuki-bibliotheca-ui/pull/215, este issue así como está se pudo reproducir. Parece que está funcionando ahora
